fix bug
GlodBlock/DeepMobEvolution-Blood pull request #4
Opened 2023-03-14 11:11 UTC by asdflj

fix bug

2023-03-14 11:44 UTC, GlodBlock requested changes

2023-03-14 11:44 UTC, GlodBlock commented on src/main/java/com/glodblock/github/dmeblood/common/inventory/SoulGemInputHandler.java
> +        return null;
return empty stack

2023-03-14 11:44 UTC, GlodBlock commented on src/main/java/com/glodblock/github/dmeblood/common/inventory/SoulGemInputHandler.java
> +        if(gemStack == null) return false;
check empty

2023-03-15 05:57 UTC, asdflj commented
修好了

2023-03-15 06:51 UTC, GlodBlock approved these changes

2023-03-15 06:51 UTC, merged